### PR TITLE
Pad syscall correctly in getTermWindowSize

### LINKED ISSUE #33: FYI: gocui triggers a bug in Go 1.13 (pre-release)
This is a heads up that gocui appears to trigger a bug in Go 1.13 (at least rc1), so if folks come to this repo and complain about crashes, you'll know what's happening.

The issue is reported upstream at https://github.com/golang/go/issues/33841.

Feel free to close this issue any time once you've seen it.

### PR DESCRIPTION
**Pull request by josharian**
Fixes #33

Given that 1.13 comes out soon, it is probably worth cutting a point release after merging this.

### CODE REVIEW

File: gui_others.go [hunk 1]
```diff
@@ -21,6 +21,7 @@ func (g *Gui) getTermWindowSize() (int, int, error) {
 	var sz struct {
 		rows uint16
 		cols uint16
+		pad  [2]uint16 // to match underlying syscall; see https://github.com/awesome-gocui/gocui/issues/33
```
Comment (golangcibot) [inline gui_others.go]: U1000: field `pad` is unused (from `unused`)

**Review by mjarkk — APPROVED** [review]
LGTM

**Review by glvr182 — APPROVED** [review]
